### ISSUE TITLE
Erreur 500 avec un jour supérieur à 12

### ISSUE THREAD

**Issue by Maredius** [florianzemma/CoronavirusAPI-France#10]
Bonjour,

Les requêtes utilisant la date retournent une erreur 500 lorsque le jour n'est pas compris entre 1 et 12 inclus. 
Exemple, en respectant bien le format DD-MM-AAAA de la date :
https://coronavirusapifr.herokuapp.com/data/france-by-date/14-10-2021

Avec une date comprise entre 1 et 12 cela marche très bien : 
https://coronavirusapifr.herokuapp.com/data/france-by-date/12-10-2021

L'erreur pourrait être du à une confusion date/mois quelque part dans le code (d'où la limitation à 12).

**Comment by florianzemma** [comment]
Bonjour,

Effectivement problème avec les dates merci de l’avoir repéré.
Je passe un fixe dans la journée.

Bonne journée,
Florian

**Comment by florianzemma** [comment]
Erreur corrigée ce jour

Vous pouvez utiliser normalement l'api avec des jours supérieurs a 12.
