### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by Romain-lab** [florianzemma/CoronavirusAPI-France#13]
Bonjour,

Je tente d'utiliser votre API sur un projet perso et je suis actuellement confronté à cette erreur : 

Access to XMLHttpRequest at 'https://coronavirusapifr.herokuapp.com/data/live/france' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Bonne journée,
Romain.

**Comment by florianzemma** [comment]
Bonjour Romain,

J'ai activé les CORS dans l'application vous devriez désormais pouvoir appeler l'url.
Je vous laisse me tenir au courant.

Bonne journée, 
Florian.

**Comment by Romain-lab** [comment]
Bonjour,

Je vous confirme que ça fonctionne désormais.
Merci pour votre réactivité.

Bonne journée,
Romain.
