### ISSUE TITLE
Problème API sur départements

### ISSUE THREAD

**Issue by elreviae** [florianzemma/CoronavirusAPI-France#15]
Bonjour,
Je suis utilisateur de votre API, merci pour tout ce travail.
Cependant j'ai noté un soucis sur la route suivante : https://coronavirusapifr.herokuapp.com/data/live/departements

Ce endpoints ne répond plus du tout actuellement.

Merci d'avance !

**Comment by florianzemma** [comment]
Bonjour Maxime,

Merci d'avoir signalé le problème, tout est rentrer dans l'ordre aujourd'hui sûrement un problème temporaire au niveaux des données du côté de Santé Publique France.

Bonne journée :)
