### ISSUE TITLE
API ne fonctionne pas

### ISSUE THREAD

**Issue by strabel2** [florianzemma/CoronavirusAPI-France#2]
Cette page d'API ne fonctionne pas

 "https://coronavirusapi-france.now.sh/AllData"

**Comment by florianzemma** [comment]
Salut , oui je viens de voir la réponse renvoyée est trop lourde il faut que je fasse un correctif

**Comment by strabel2** [comment]
Bonsoir,je suis désolée de vous déranger encore une fois.
Est ce que vous pouvez faire quelque chose pour votre application.
Toutes mes excuses.

**Comment by florianzemma** [comment]
Bonsoir,

Malheureusement la solution utilisée pour hébergé l'API ne me permet pas de corriger cette issue.

Désolé
Bonne journée
Florian
