### ISSUE TITLE
return error 500

### ISSUE THREAD

**Issue by MiroYld** [florianzemma/CoronavirusAPI-France#28]
Bonjour,
l'API renvoie une erreur 500 sur toutes les urls : https://coronavirusapifr.herokuapp.com/data/live/departements

**Comment by florianzemma** [comment]
Bonjour,

L'API avait effectivement un problème avec aws.
Le problème est réglé et l'API marche de nouveau, cependant la mise à jour des données n'a pas du se faire il n'y aura donc pas de données pour aujourd'hui je pense

**Comment by MiroYld** [comment]
L'api ne peut-elle pas fetch les données toutes les heures ?

**Comment by florianzemma** [comment]
Ce serait effectivement possible mais inutile, le jeux de données qui est requêté est mise à jour une fois par jour je récupères les données depuis ce fichier tous les jours a minuit

**Comment by MiroYld** [comment]
Ok, je comprend.
Merci pour la réactivité :)
