### ISSUE TITLE
API vide

### ISSUE THREAD

**Issue by Gazier9** [florianzemma/CoronavirusAPI-France#3]
Bonjour, 
Depuis  hier, l'API est vide. Est ce volontaire?
L'API continuera d'être disponible ?
Merci pour votre réponse

**Comment by florianzemma** [comment]
Bonjour, 

Effectivement aucunes données n’ont été fournies depuis le 31/12/2020 , cela doit être du aux congés de fin d’année , je pense que tout rentrera dans l’ordre lundi.

Bonne soirée :)

**Comment by Gazier9** [comment]
Bonjour, 

Je vous remercie pour votre réponse. 
Je vais dès maintenant mettre une étoile.
Merci pour votre API.

Bonne soirée, 
Alex

**Comment by Nekzuris** [comment]
Les données ont pourtant bien été publié ici : https://dashboard.covid19.data.gouv.fr/vue-d-ensemble?location=FRA

**Comment by florianzemma** [comment]
J’utilise les jeux de données OpenCOVID19 et j’ai bien vérifier hier les dernières informations dans ce jeux de données s’arrêtent au 31/12/2020 actuellement

**Comment by florianzemma** [comment]
Bonjour,

Tout est rentré dans l'ordre ce matin.

Bonne journée
Florian

**Comment by Gazier9** [comment]
Bonjour, 
Merci Florian pour ta disponibilité et ta réactivité!
Bonne journée
Alex

**Comment by florianzemma** [comment]
Bonjour,
Avec plaisir,
bonne journée a toi aussi !
Florian
