### ISSUE TITLE
Problème sur la finition de mon projet

### ISSUE THREAD

**Issue by Amon-B** [florianzemma/CoronavirusAPI-France#4]
Rebonjour Mr Gailleton,
J’espère que tout se passe pour le mieux, que votre réveillon c’est bien dérouler en cette période de confinement, et vous souhaite une bonne nouvelle année. Je vous contact aujourd’hui pour vous faire part d’un problème. Depuis que le message "Due to security reasons, the creation of new content is currently disabled" est présent sur le site data.gouv.fr, les informations de l’API ne sont plus disponibles. Je suis actuellement sur la finition de mon projet sur la réalisation d’un site informative du développement du coronavirus en France (que je devrais finir, rendre et présenter dans 2 semaines). Serait-ce possible de savoir quelle est la nature du problème en question et quand seront les informations de l’API à nouveau disponibles, pour ainsi envisager et rédiger la finition de mon projet. 
Bien Cordialement,
Amon BERBEROVIC

**Comment by florianzemma** [comment]
Bonjour Amon,

Effectivement aucune données n’ont été fournis depuis le 31/12/2020 , je pense que cela est due aux congés de fin d’année et que tout rentrera dans l’ordre d’ici lundi.

J’espère que vous aussi avez passer une bon réveillon et je vous souhaite également une bonne année.

Bonne soirée :) 
Florian.

**Comment by florianzemma** [comment]
Bonjour, 

Tout est rentré dans l'ordre ce matin.

Bonne journée
Florian
