### ISSUE TITLE
Source non disponible

### ISSUE THREAD

**Issue by SierraDeltAa** [florianzemma/CoronavirusAPI-France#6]
Bonjour, 

l'api ne fournit plus de données depuis le 12 aôut 2021.

un array vide est envoyé à la place.

est-ce volontaire ? Merci de votre réponse et du travail fourni jusqu'ici . 

:)

**Comment by cobacdavid** [comment]
Il semble que les fichiers sources (https://github.com/opencovid19-fr/data/tree/master/dist) ne soient plus actualisés et qu'ils soient en fait actualisés "à la main" (voir https://github.com/opencovid19-fr/data/blob/master/README.md avec cette phrase : 
```
Inutile de perdre du temps à écrire des scrappers, à ce stade il est plus efficace de recopier les données à la main, et d'indiquer la source.
```

**Comment by florianzemma** [comment]
Bonjour,
Désolé pour la réponse tardive, il arrive parfois que les données de l’API ne soient pas actualisées pendant quelques jours par le fournisseur de données.

Bonne soirée

**Comment by SierraDeltAa** [comment]
Bonsoir à vous,

Je vous remercie pour votre réponse, oui j'avais pu voir cela je suis allé
voir directement chez le fournisseur de données pour y récupérer l'API.
C'est bon vous avez pu y récupérer les données de votre coté ?

Bonne soirée à vous,

Respectueusement,

Denil MERAD

Le mar. 31 août 2021 à 21:55, florianzemma ***@***.***> a
écrit :

**Comment by florianzemma** [comment]
Bonjour,

Visiblement le fournisseur de données a stopper le projet pour le moment. 

J’ai pas mal de boulot ces derniers temps et du coup peu de temps a accordé à ce side project , je vais essayer de trouver une nouvelle source et prévoir une refonte de l’API.

Bonne journée,
Florian :)

**Comment by florianzemma** [comment]
**NOUVELLE VERSION DE L'API EN LIGNE**
