### ISSUE TITLE
No data found

### ISSUE THREAD

**Issue by MiroYld** [florianzemma/CoronavirusAPI-France#9]
Bonjour,

Sur plusieurs points d'entrées, j'ai une erreur no data found. Est-ce normal ? 
Depuis symfony l'url /data/live/france me renvoi : Syntax error for "https://coronavirusapifr.herokuapp.com/data/live/france".

**Comment by florianzemma** [comment]
Bonjour,

Le cron censé récupérer les données toutes les X heures ne marche pas en étant héberger sur heroku.
L’actualisation des données requiert donc une action manuelle de ma pars actuellement je l’ai mise à jour :) 

Bonne journée

**Comment by MiroYld** [comment]
Merci de votre réactivité, et d'avoir corrigé le bug.
Grace à votre API = http://51.38.233.189/TrackerCovid19/public/index.php/home (bientôt finalisée)

Excellente journée.

**Comment by florianzemma** [comment]
Cool, content de voir que l’API est utilisée.

Excellente journée à vous aussi
